server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Yasir-Cloud9/smartVoting-spring-app-config.git
          clone-on-start: true
